# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a6665c99a30533352d2d76a19f46ba4cd6811cbae35df739ea283defe1e84de604ed84c2530662595dc7fb56731698067411f6be8fa53a7ff4c6a0926999b4

test:
  secret_key_base: 524d87efa5b31ba7dafac8342e9a8dd5a10f969351839469e289ae2a3218fdd3dae3ff995c28f5fbaf33e02777b152a1d798d863839cfb85a49c3a4b037ffef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
